<?php

namespace Database\Factories\CMS;

use App\Enums\ContentStatus;
use App\Models\CMS\Site;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\CMS\Page>
 */
class PageFactory extends Factory
{
    protected $model = \App\Models\CMS\Page::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $title = fake()->sentence(5);

        return [
            'site_id' => Site::factory(),
            'created_by' => User::factory(),
            'title' => $title,
            'slug' => '', // Will be auto-generated by model boot
            'excerpt' => fake()->paragraph(2),
            'content' => $this->generateContent(),
            'seo_title' => $title,
            'seo_description' => fake()->sentence(15),
            'seo_keywords' => implode(', ', fake()->words(5)),
            'featured_image' => fake()->imageUrl(1200, 630, 'business', true),
            'status' => ContentStatus::DRAFT,
            'published_at' => null,
            'meta_data' => [
                'author' => fake()->name(),
                'reading_time' => fake()->numberBetween(2, 10).' min',
            ],
            'order' => fake()->numberBetween(0, 100),
        ];
    }

    /**
     * Indicate that the page is published.
     */
    public function published(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => ContentStatus::PUBLISHED,
            'published_at' => now(),
        ]);
    }

    /**
     * Indicate that the page is pending approval.
     */
    public function pending(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => ContentStatus::PENDING,
        ]);
    }

    /**
     * Generate realistic HTML content.
     */
    private function generateContent(): string
    {
        $paragraphs = [];

        for ($i = 0; $i < fake()->numberBetween(3, 6); $i++) {
            $paragraphs[] = '<p>'.fake()->paragraph(fake()->numberBetween(4, 8)).'</p>';
        }

        return implode("\n", $paragraphs);
    }
}
