<?php

namespace Database\Factories\CMS;

use App\Enums\ContentStatus;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\CMS\Post>
 */
class PostFactory extends Factory
{
    protected $model = \App\Models\CMS\Post::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $title = fake()->sentence(6);

        return [
            'site_id' => 1, // Will be overridden in tests
            'category_id' => null, // Optional
            'created_by' => 1, // Default to test user
            'title' => $title,
            'slug' => '', // Will be auto-generated by model boot
            'excerpt' => fake()->paragraph(3),
            'content' => $this->generateContent(),
            'seo_title' => $title,
            'seo_description' => fake()->sentence(15),
            'seo_keywords' => implode(', ', fake()->words(5)),
            'featured_image' => fake()->imageUrl(1200, 630, 'blog', true),
            'status' => ContentStatus::DRAFT,
            'published_at' => null,
            'tags' => fake()->words(fake()->numberBetween(3, 6)),
            'meta_data' => [
                'author' => fake()->name(),
                'reading_time' => fake()->numberBetween(3, 15).' min',
                'views' => fake()->numberBetween(0, 1000),
            ],
        ];
    }

    /**
     * Indicate that the post is published.
     */
    public function published(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => ContentStatus::PUBLISHED,
            'published_at' => now()->subDays(fake()->numberBetween(0, 30)),
        ]);
    }

    /**
     * Indicate that the post is pending approval.
     */
    public function pending(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => ContentStatus::PENDING,
        ]);
    }

    /**
     * Generate realistic HTML content with headings and lists.
     */
    private function generateContent(): string
    {
        $content = [];

        // Introduction
        $content[] = '<p>'.fake()->paragraph(5).'</p>';

        // Main content sections
        for ($i = 0; $i < fake()->numberBetween(2, 4); $i++) {
            $content[] = '<h2>'.fake()->sentence(4).'</h2>';
            $content[] = '<p>'.fake()->paragraph(6).'</p>';

            // Sometimes add a list
            if (fake()->boolean(40)) {
                $content[] = '<ul>';
                for ($j = 0; $j < fake()->numberBetween(3, 5); $j++) {
                    $content[] = '  <li>'.fake()->sentence(fake()->numberBetween(4, 8)).'</li>';
                }
                $content[] = '</ul>';
            }

            $content[] = '<p>'.fake()->paragraph(5).'</p>';
        }

        // Conclusion
        $content[] = '<p>'.fake()->paragraph(4).'</p>';

        return implode("\n", $content);
    }
}
